const nodemailer = require("nodemailer")

const transport = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    auth: {
        user: "sunny25@ethereal.email", // Generated by ethereal
        pass: "cnDtv7hXzA6Wwd9tTU"  // Generated by ethereal
    }
});

let mailOptions = {
    from: '"Example Team" <from@example.com>',
    to: 'user1@example.com, user2@example.com',
    subject: "Nice Nodemailer test",
    text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
    html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer',

    //Optional properties let you add specific content types or inline images. 
    // contentType: if you don’t set it, it will be inferred from the filename property
    // An array of attachments
    attachments: [
        // String attachment
        {
            filename: 'notes.txt',
            content: 'new important notes',
            contentType: 'text/plain' // optional, would be detected from the filename
        }
    ]
}


transport.sendMail(mailOptions, (error, info) => {
    if(error) {
        return console.log(error);
    }
    console.log('Message Sent: %s', info.messageId)
})

