const express = require("express");
const app = express();
const router = express.Router();
const nodemailer = require("nodemailer")
const creds = require("./.env")


const transport = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    auth: {
        user: creds.USER, // Generated by ethereal
        pass: creds.PASS // Generated by ethereal
    }
});

const transporter = nodemailer.createTransport(transport)

router.post("/send", (req, res, next) => {
    let name = req.body.name
    let email = req.body.email
    let message = req.body.message
    let content = `name: ${name} \n email: ${email} \n message: ${content}`


    let mail = {
        from: name,
        to: "jlbroughton88@gmail.com",
        subject: "Test from contact form",
        text: 'Hey bud',
        html: content
    }

    transporter.sendMail(mail, (err, data) => {
        if (err) {
            res.json({
                msg: "Message failed"
            })
        } else {
            res.json({
                msg: "Message succeeded!"
            })
        }
    })
})


app.listen(5007, () => {
    console.log("Server listening on port 5007")
})