const express = require("express");
const router = express.Router();
const nodemailer = require("nodemailer")
const creds = require("../.env")

const transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false, 
    auth: {
        user: creds.USER, // Generated by ethereal
        pass: creds.PASS // Generated by ethereal
    }
});


transporter.verify((err, success) => {
    if(err) {
        console.log(err)
    } else {
        console.log("Server is ready to take messages")
    }
})

router.post("/send", (req, res, next) => {
    let name = req.body.name
    let email = req.body.email
    let message = req.body.message
    let content = `name: ${name} \n email: ${email} \n message: ${message}`

    let mail = {
        from: name,
        to: "jlbroughton88@gmail.com",
        subject: "Test from contact form",
        text: content
    }

    transporter.sendMail(mail, (err, data) => {
        if (err) {
            res.json({
                msg: "Message failed"
            })
        } else {
            res.json({
                msg: "Message succeeded!"
            })
        }
    })
})

module.exports = router;